import { fetchTopRisks, fetchHealth } from "@/lib/api";
import { Header } from "@/components/Header";
import { RiskCard } from "@/components/RiskCard";
import { TIER_CONFIG } from "@/lib/format";
import type { Tier } from "@/lib/types";

// Force dynamic rendering — risk data is operational and changes;
// we don't want Next.js to statically pre-render with stale data at build time.
export const dynamic = "force-dynamic";
export const revalidate = 0;

// Tier priority for the top accent bar — act_now is most severe.
const TIER_SEVERITY: Tier[] = ["act_now", "act_soon", "track", "monitor"];

export default async function Page() {
  // Fire both fetches in parallel — they're independent.
  const [risksResult, healthResult] = await Promise.all([
    fetchTopRisks(5),
    fetchHealth(),
  ]);

  // Hard failure case — both endpoints unreachable or risks failed.
  if (!risksResult.data) {
    return <ErrorState error={risksResult.error ?? "No data"} />;
  }

  const risks = risksResult.data;
  const health = healthResult.data;

  // Determine the worst active tier for the accent bar.
  const worstTier = TIER_SEVERITY.find((t) =>
    risks.some((r) => r.tier === t),
  );

  return (
    <div className="relative z-10 min-h-screen">
      {/* Threat-level accent bar */}
      {worstTier && (
        <div
          className="h-[2px] w-full"
          style={{ backgroundColor: TIER_CONFIG[worstTier].accent }}
          aria-label={`Highest threat level: ${TIER_CONFIG[worstTier].label}`}
        />
      )}

      <Header risks={risks} health={health} />

      <main className="px-6 py-10">
        <div className="max-w-[1180px] mx-auto">
          {risks.length === 0 ? (
            <EmptyState />
          ) : (
            <div className="stagger space-y-4">
              {risks.map((risk) => (
                <RiskCard key={`${risk.asset_id}-${risk.vuln_id}`} risk={risk} />
              ))}
            </div>
          )}

          <Footer />
        </div>
      </main>
    </div>
  );
}

function ErrorState({ error }: { error: string }) {
  return (
    <main className="relative z-10 min-h-screen flex items-center justify-center px-6">
      <div className="max-w-md text-center">
        <div className="inline-flex items-center gap-2 font-mono text-xs uppercase tracking-wider text-tier-act-now mb-6">
          <span className="inline-block h-2 w-2 rounded-full bg-tier-act-now animate-pulse-soft" />
          pipeline unreachable
        </div>
        <h1 className="font-sans text-3xl font-semibold text-ink mb-3">
          Risk data unavailable
        </h1>
        <p className="text-ink-muted text-base mb-6 leading-relaxed">
          The backend API at{" "}
          <code className="font-mono text-ink-muted bg-bg-raised px-1.5 py-0.5 border border-bg-border text-sm">
            NEXT_PUBLIC_API_URL
          </code>{" "}
          did not respond.
        </p>
        <pre className="font-mono text-sm text-tier-act-now/80 bg-bg-raised border border-tier-act-now/20 p-4 text-left overflow-auto">
          {error}
        </pre>
      </div>
    </main>
  );
}

function EmptyState() {
  return (
    <div className="border border-bg-border bg-bg-raised px-6 py-16 text-center">
      <div className="eyebrow mb-2">no risks returned</div>
      <p className="text-ink-muted text-base">
        The pipeline ran but produced no ranked risks. Check the backend logs.
      </p>
    </div>
  );
}

function Footer() {
  return (
    <footer className="mt-16 pt-8 border-t border-bg-border">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-ink-dim leading-relaxed">
        <div>
          <div className="eyebrow mb-2">methodology</div>
          <p>
            Risks are scored through deterministic tier gates (act_now /
            act_soon / track / monitor) and a weighted score within each
            tier. No LLM participates in ranking. Explanations are
            generated by Groq Llama 3.3 70B (Gemini 2.5 Flash configured
            as primary, falls back to Groq under free-tier quota) and
            citation-validated before display.
          </p>
        </div>
        <div>
          <div className="eyebrow mb-2">data sources</div>
          <p>
            CISA Known Exploited Vulnerabilities catalog, NIST SP 800-53
            Rev 5, internal asset/vulnerability inventory, MDR threat
            advisory. See{" "}
            <a href="https://github.com/MuaazSM/tawasolpay-risk-assistant/blob/main/README.md" target="_blank" rel="noopener noreferrer" className="text-ink-muted underline hover:text-ink-default">README.md</a>{" "}
            for architecture and decisions.
          </p>
        </div>
      </div>

      <div className="mt-8 pt-4 border-t border-bg-border/50 flex items-center justify-between">
        <span className="font-mono text-[11px] uppercase tracking-wider text-ink-faint">
          TawasolPay Cyber Risk Assessment
        </span>
        <span className="font-mono text-[11px] text-ink-faint">
          Deterministic scoring · NIST 800-53 RAG · Faithfulness-validated
        </span>
      </div>
    </footer>
  );
}
